# cSpell:ignore github
CacheExpires: 9000h # ~ 12 months
DirectoryPath: build
TestFilesConcurrently: true
IgnoreURLs: # list of regexes of URLs or path to be ignored
  - ^https?://localhost
  - \?no-link-check
  # Social media links that may be rate-limited
  - ^https://(www\.)?linkedin\.com
  - ^https://(www\.)?twitter\.com
  - ^https://(www\.)?facebook\.com
  - ^https://(www\.)?youtube\.com
  - ^https://(www\.)?medium\.com
  - ^https://(www\.)?instagram\.com
